const { createPlugin } = require('stylelint');

const ruleNames = [
	'at-rule-name-case',
	'at-rule-name-space-after',
	'at-rule-semicolon-newline-after',
	'block-closing-brace-newline-after',
	'block-closing-brace-newline-before',
	'block-closing-brace-space-before',
	'block-opening-brace-newline-after',
	'block-opening-brace-space-after',
	'block-opening-brace-space-before',
	'color-hex-case',
	'declaration-bang-space-after',
	'declaration-bang-space-before',
	'declaration-block-semicolon-newline-after',
	'declaration-block-semicolon-space-after',
	'declaration-block-semicolon-space-before',
	'declaration-block-trailing-semicolon',
	'declaration-colon-newline-after',
	'declaration-colon-space-after',
	'declaration-colon-space-before',
	'function-comma-newline-after',
	'function-comma-space-after',
	'function-comma-space-before',
	'function-max-empty-lines',
	'function-parentheses-newline-inside',
	'function-parentheses-space-inside',
	'function-whitespace-after',
	'indentation',
	'max-empty-lines',
	'media-feature-colon-space-after',
	'media-feature-colon-space-before',
	'media-feature-name-case',
	'media-feature-parentheses-space-inside',
	'media-feature-range-operator-space-after',
	'media-feature-range-operator-space-before',
	'media-query-list-comma-newline-after',
	'media-query-list-comma-space-after',
	'media-query-list-comma-space-before',
	'no-eol-whitespace',
	'no-extra-semicolons',
	'number-leading-zero',
	'number-no-trailing-zeros',
	'property-case',
	'selector-attribute-brackets-space-inside',
	'selector-attribute-operator-space-after',
	'selector-attribute-operator-space-before',
	'selector-combinator-space-after',
	'selector-combinator-space-before',
	'selector-descendant-combinator-no-non-space',
	'selector-list-comma-space-before',
	'selector-max-empty-lines',
	'selector-pseudo-class-case',
	'selector-pseudo-class-parentheses-space-inside',
	'selector-pseudo-element-case',
	'unit-case',
	'value-list-comma-newline-after',
	'value-list-comma-space-after',
	'value-list-comma-space-before',
	'value-list-max-empty-lines'
];

module.exports = ruleNames.map(name => {
	return createPlugin(`d2l/${name}`, require(`./${name}`));
});
